### ISSUE TITLE
[Feat] LogDetailView 추가

### ISSUE THREAD

**Issue by OLING99** [DeveloperAcademy-POSTECH/MC3-Team17-Modera#12]
## Description
- LogDetailView 추가

## Task
-  [ ] 새 메모 적고 저장
-  [ ] 새 메모 작성하는 textfield 디자인 수정
-  [ ] 날짜 data 받기
-  [ ] ellipsis button -  반모달창(삭제하기, 사견 작성하기, 북마크하기) 
-  [ ] 검색기능
