### ISSUE TITLE
[Feat] 설정하기 페이지

### ISSUE THREAD

**Issue by OLING99** [DeveloperAcademy-POSTECH/MC3-Team17-Modera#20]
## Description
온보딩, 설정하기 화면

## Task
-  [ ] 온보딩 화면 뷰 그리기
-  [ ] 클라우드 동기화 뷰 그리기
-  [ ] 설정하기 페이지 뷰 그리기
-  [ ] 단축어 추가 링크 넣기
-  [ ] 워치 설정앱으로 연결하기
