### ISSUE TITLE
[Feat] 디테일 뷰 viewModel 구현 및 연동

### ISSUE THREAD

**Issue by sozohoy** [DeveloperAcademy-POSTECH/MC3-Team17-Modera#22]
## Description
- View가 머지됨에 따라 기능과 뷰를 연결합니다.

## Task
-  [x] 디테일 뷰 디자인 반영
-  [x] mainView <-> DetailView 연결
-  [x] DetailView 제목 작성/수정 <-> 메인 업데이트
-  [x] 일지 작성/수정/삭제 <-> 메인 업데이트
-  [x] 사견 작성/수정/삭제
-  [x] 일지, 사견 불러오기(날짜 별 구분)
