### ISSUE TITLE
[Feat] 워치와 클라우드킷 데이터 연결하기

### ISSUE THREAD

**Issue by cutthebutter** [DeveloperAcademy-POSTECH/MC3-Team17-Modera#28]
## Description
워치와 클라우드킷 데이터를 연결합니다. 
## Task
-  [x] 타이틀 불러오기 + 타이틀 새로 만들기 
-  [x] 새로운 메모 저장하기
     - [x] 오늘 기록이 없는 경우
     - [x] #29
- [ ] 로그 메모 기록 불러오기

**Comment by cutthebutter** [comment]
CK.ID 해결해야함

**Comment by cutthebutter** [comment]
다시 워치 커넥티비티로 연결해야 함
