### ISSUE TITLE
[Feat] CloudKit 데이터 연동

### ISSUE THREAD

**Issue by sozohoy** [DeveloperAcademy-POSTECH/MC3-Team17-Modera#9]
## Description
- 메인 뷰와 CloudKit을 연동해서 데이터를 출력할 예정입니다.

## Task
-  [x] LogViewModel - CloudKit 데이터 호출
-  [x] CloudKit CRU(Mock 데이터) // Delete는 데이터가 좀 쌓인 후 구현 예정
-  [x] ViewModel CRU, 카테고리 이동 구현 // Delete는 데이터가 좀 쌓인 후 구현 예정
